apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: ai-assistant
spec:
  version: "0.2.1-SNAPSHOT"
  enabled: true
  requires: ">=2.24.0"
  author:
    name: rainwu
    website: https://github.com/rainwu
  logo: /plugins/ai-assistant/assets/res/images/logo.png
  homepage: https://github.com/rainwu/plugin-ai-assistant#readme
  displayName: "AI 智能助手"
  description: "为 Halo 博客提供 AI 智能问答、文档智能编辑、AI 摘要等功能，支持对接主流 AI 大模型厂商"
  configMapName: ai-assistant-configmap
  license:
    - name: "GPL-3.0"
      url: "https://github.com/rainwu/plugin-ai-assistant/blob/main/LICENSE"
